### PR TITLE
add scaling laws notebook

### PR DESCRIPTION
**Pull request by lvwerra**
Notebook to replicate Chinchilla scaling laws. Follows steps in D.2 (however for pass@k and its inverse rather than loss).

### CODE REVIEW

**Comment by Randl** [comment]
The csv file is missing?

**Comment by lvwerra** [comment]
Indeed, added it here: https://huggingface.co/datasets/bigcode/scaling-laws-exp/tree/main

**Comment by harm-devries** [comment]
Just pushed a fix for the optimization issues in the scaling laws. Fitted function now looks as follows:

Unknown-12

**Comment by Randl** [comment]
Probably better make x-axis logscale

**Review by loubnabnl — APPROVED** [review]

**Pull request merged**
