### PR TITLE
Add decontamination code

### PR DESCRIPTION
**Pull request by ChenghaoMou**
Similar to deduplication, but use benchmark datasets as index.

Used for #13

### CODE REVIEW

**Review by loubnabnl — APPROVED** [review]
Great, thanks for adding this!
@RaymondLi0 Maybe we can add your exact matching script too?

**Comment by RaymondLi0** [comment]
Thank you @ChenghaoMou ! Sure, maybe we can first merge this PR, then I'll upload my script too? (this PR is from a fork, so otherwise I'd need to commit directly in Chenghao's fork)

**Comment by ChenghaoMou** [comment]
I don't have write access for merge, please help.

**Comment by loubnabnl** [comment]
Ah sorry thought you could merge when the PR's approved

**Pull request merged**
