### PR TITLE
MQA experiments on AWS SageMaker Lab

### LINKED ISSUE #20: cannot import AttentionType from gpt2
Loading `multi_query_experiments.profile_hf_generate` results in 

```
ImportError: cannot import name 'AttentionType' from 'transformers.models.gpt2.modeling_gpt2'
```

I find this puzzling since this class is not exported by `transformers` 4.20.0 

Are you using a custom fork of transformers by chance?

### PR DESCRIPTION
**Pull request by ocramz**
* ensure experiments can run in a SageMaker environment as well (writable directories for the transformers cache, corresponding env vars etc.)
* ensure we can fall back to CPU if GPU not present
* add a "open in SageMaker" button https://github.com/bigcode-project/bigcode-analysis/compare/main...ocramz:sagemaker?expand=1#diff-fba51864a7a061cb370cc220d136879290a9451229a9286a4295c901ba22f1ecR12 ~~(correct link pending)~~
* add benchmarking of decoder
* documentation

(subsumes #21 and fixes #20 too)

### CODE REVIEW

**Comment by loubnabnl** [comment]
Thanks for working on this. Tagging @bigximik to check the changes. 
Also can you move the notebook `profile_mqa` inside `multi_query_experiments` folder? so that we separate experiments

**Comment by ocramz** [comment]
@loubnabnl done!

**Comment by bigximik** [comment]
Thanks @ocramz. Looks nice

**Comment by ocramz** [comment]
Thank you @bigximik , could you approve and merge?

**Review by loubnabnl — APPROVED** [review]
Approved!

**Pull request merged**
